// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"git.sqcorp.co/cash/cash-service-operator/pkg/apis/cloud/v1alpha1.CashService":       schema_pkg_apis_cloud_v1alpha1_CashService(ref),
		"git.sqcorp.co/cash/cash-service-operator/pkg/apis/cloud/v1alpha1.CashServiceSpec":   schema_pkg_apis_cloud_v1alpha1_CashServiceSpec(ref),
		"git.sqcorp.co/cash/cash-service-operator/pkg/apis/cloud/v1alpha1.CashServiceStatus": schema_pkg_apis_cloud_v1alpha1_CashServiceStatus(ref),
	}
}

func schema_pkg_apis_cloud_v1alpha1_CashService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CashService is the Schema for the cashservices API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("git.sqcorp.co/cash/cash-service-operator/pkg/apis/cloud/v1alpha1.CashServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("git.sqcorp.co/cash/cash-service-operator/pkg/apis/cloud/v1alpha1.CashServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"git.sqcorp.co/cash/cash-service-operator/pkg/apis/cloud/v1alpha1.CashServiceSpec", "git.sqcorp.co/cash/cash-service-operator/pkg/apis/cloud/v1alpha1.CashServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cloud_v1alpha1_CashServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CashServiceSpec defines the desired state of CashService",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_cloud_v1alpha1_CashServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CashServiceStatus defines the observed state of CashService",
				Type:        []string{"object"},
			},
		},
	}
}
