// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/apps/v1"
	v2beta2 "k8s.io/api/autoscaling/v2beta2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashService) DeepCopyInto(out *CashService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashService.
func (in *CashService) DeepCopy() *CashService {
	if in == nil {
		return nil
	}
	out := new(CashService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CashService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceAutomaticDeployment) DeepCopyInto(out *CashServiceAutomaticDeployment) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceAutomaticDeployment.
func (in *CashServiceAutomaticDeployment) DeepCopy() *CashServiceAutomaticDeployment {
	if in == nil {
		return nil
	}
	out := new(CashServiceAutomaticDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceAutoscaling) DeepCopyInto(out *CashServiceAutoscaling) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2beta2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceAutoscaling.
func (in *CashServiceAutoscaling) DeepCopy() *CashServiceAutoscaling {
	if in == nil {
		return nil
	}
	out := new(CashServiceAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceContainer) DeepCopyInto(out *CashServiceContainer) {
	*out = *in
	out.Deployment = in.Deployment
	in.Resources.DeepCopyInto(&out.Resources)
	out.Debug = in.Debug
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceContainer.
func (in *CashServiceContainer) DeepCopy() *CashServiceContainer {
	if in == nil {
		return nil
	}
	out := new(CashServiceContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceDebug) DeepCopyInto(out *CashServiceDebug) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceDebug.
func (in *CashServiceDebug) DeepCopy() *CashServiceDebug {
	if in == nil {
		return nil
	}
	out := new(CashServiceDebug)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceDeployment) DeepCopyInto(out *CashServiceDeployment) {
	*out = *in
	out.Manual = in.Manual
	out.Automatic = in.Automatic
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceDeployment.
func (in *CashServiceDeployment) DeepCopy() *CashServiceDeployment {
	if in == nil {
		return nil
	}
	out := new(CashServiceDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceList) DeepCopyInto(out *CashServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CashService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceList.
func (in *CashServiceList) DeepCopy() *CashServiceList {
	if in == nil {
		return nil
	}
	out := new(CashServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CashServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceManualDeployment) DeepCopyInto(out *CashServiceManualDeployment) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceManualDeployment.
func (in *CashServiceManualDeployment) DeepCopy() *CashServiceManualDeployment {
	if in == nil {
		return nil
	}
	out := new(CashServiceManualDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceSpec) DeepCopyInto(out *CashServiceSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Container.DeepCopyInto(&out.Container)
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	in.RollingUpdate.DeepCopyInto(&out.RollingUpdate)
	in.Environment.DeepCopyInto(&out.Environment)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceSpec.
func (in *CashServiceSpec) DeepCopy() *CashServiceSpec {
	if in == nil {
		return nil
	}
	out := new(CashServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CashServiceStatus) DeepCopyInto(out *CashServiceStatus) {
	*out = *in
	if in.Deployments != nil {
		in, out := &in.Deployments, &out.Deployments
		*out = make(map[string]v1.DeploymentStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CashServiceStatus.
func (in *CashServiceStatus) DeepCopy() *CashServiceStatus {
	if in == nil {
		return nil
	}
	out := new(CashServiceStatus)
	in.DeepCopyInto(out)
	return out
}
