name: Lint
on: [push]
jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
   
    - name: Set up environment
      run: . build/setup_env

    - name: Lint
      run: . build/setup_env; make lint
