name: Unit Tests
on: [push]
jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
   
    - name: Set up environment
      run: . build/setup_env

    - name: Test
      run: . build/setup_env; make test
